### ISSUE TITLE
Initializing a population with empirical genotype frequencies

### ISSUE THREAD

**Issue by LozWhite** [BoPeng/simuPOP#20]
Hello,
My name is Lauren, I am currently trying to use simuPOP, but have have not been able to resolve an issue on my own. 

I have genotyped ~3000 SNPs in 20 individuals from a small population of a threatened mammal species (population size of roughly 1000). I would like simulate how the genotypes and allele frequencies at these markers are likely to change in the future under different scenarios of population growth or decline. I am having trouble figuring out how to set up the initial population for simulation using my empirical data.

I would like to use the empirical genotype frequencies at each locus from the sample of individuals genotyped to set up the original population for simulation, but with a population size that reflects the true population size of ~1000 individuals. Its important that I use the genotype frequencies, and not allele frequencies, to properly represent that current level of inbreeding in the population.
 
Is something like this possible using simuPOP? and if so, could I please be pointed in the right direction to set it up? 

Thank you for your time
Cheers
-Lauren

**Comment by BoPeng** [comment]
You can achieve this in two ways, the first is to import your sample as a smaller population and "expand' it. This might or might not be easy depending on the format of your input file. You can [import population from a few supported formats](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch7_sec2.html#import-simupop-population-from-files-in-genepop-phylip-and-fstat-formats-function-importpopulation), or write your own function to import (e.g. [loadHapMap3](http://simupop.sourceforge.net/Cookbook/SimuGWAS)). After you obtained your population, you can do [`pop.resize(propagate=True)`](http://simupop.sourceforge.net/manual_svn/build/refManual_ch2_sec1.html#class-population).

Another way is to initialize populations randomly with given genotype frequency. Basically you would need to have 3000 [InitGenotype](http://simupop.sourceforge.net/manual_svn/build/refManual_ch3_sec2.html#class-initgenotype) operator with parameters `genotypes` and `loci`. This is not as scary as it sounds because you only need to do something like

```
initOps = [InitGenotye(genotypes=freq[i], loci=i) for i in range(3000)]
```
if you have `freq[i]` prepared before.

Hope this helps,

**Comment by LozWhite** [comment]
Thanks so much for the quick reply! 

I think your second suggestions is the way to go.
For clarification, if I had four loci with genotype frequencies:
aa	aA	AA
0	0.19	0.81
0.25	0.25	0.5
0.08	0.22	0.7
0.42	0.33	0.25

How would I prepare freq[i].

Thank you again,
Lauren

**Comment by BoPeng** [comment]
Just make a nested list of 

```
freq = [
[0,	0.19,	0.81],
[0.25,	0.25,	0.5],
[0.08,	0.22,	0.7],
[0.42,	0.33,	0.25],
]
```

so that `freq[i]` points to the genotype frequencies of the `i`th locus.

**Comment by LozWhite** [comment]
Thank you, this has been very helpful

**Comment by LozWhite** [comment]
Hi Bo, I am still having trouble with this problem.

In a population of 20 individuals with 1 locus: if I would like to initialise the genotypes (or haplotypes, I'm sorry I may have been using the incorrect terminology in this context) of homozygote [00], heterozygote [01] and homozygote alternate [11], at frequencies 0f 0.0, 0.25 and 0.75 respectively, what would be the correct call?

I have been trying
sim.initGenotype(pop, haplotypes=[[0,0], [0,1], [1,1]],  freq=[0,   0.25,   0.75], loci=0)

I expect 15 of the individuals to have the genotype [11] and 5 to have [01], but this is not the case. The numbers always come out slightly off and I sometimes get individuals with the [00] genotype. 

Thank you again for your time.

Cheers

**Comment by BoPeng** [comment]
Did you try parameter prop (proportion)?

**Comment by LozWhite** [comment]
Yes, the numbers were off.

**Comment by BoPeng** [comment]
Oops, haplotypes are alleles on the same strand, you need to specify genotypes here.

**Comment by LozWhite** [comment]
ah ok!
but I cannot seem to use genotype and freq in the same call.
In my test population with only one locus, genotype=(0,0,01,11), creates:

SubPopulation 0 (), 20 Individuals:
   0: MU 0 | 0
   1: MU 0 | 1
   2: MU 1 | 1
   3: MU 0 | 0
   4: MU 0 | 1
   5: MU 1 | 1
   6: MU 0 | 0
   7: MU 0 | 1
   8: MU 1 | 1
   9: MU 0 | 0
  10: MU 0 | 1
  11: MU 1 | 1
  12: MU 0 | 0
  13: MU 0 | 1
  14: MU 1 | 1
  15: MU 0 | 0
  16: MU 0 | 1
  17: MU 1 | 1
  18: MU 0 | 0
  19: MU 0 | 1

How can I use the genotype call to create a population with 75% of
individuals having the genotype 1|1 and 25% having the genotype 0|1.

I eventually want to extend this to create a population with many loci with
different genotype frequencies.

Cheers

**Comment by BoPeng** [comment]
Hi, Lauren,

My apologies. I was on the road and had to be brief. Unfortunately `InitGenotype` 's `prop` and `freq` options only support alleles and haplotypes, not genotypes. I cannot recall the exact reasons for this but perhaps because there is already a `genotype` option, which means something else (it basically uses a genotype array to fill genotypes sequentially). This has not been a problem because we almost always assume HW equilibrium so initializing HW genotypes is equivalent to initializing alleles by allele frequencies. Also, the combination of genotypes increase quickly in a multi-allele setting, which makes it impractical to specify all genotypes and their frequencies (or proportions).

That said, if you really need to initialize randomly, and with specified frequencies, you can do it manually with something like:

```
from simuPOP.util import WeightedSampler

for i in range(nLoci):
    sampler = WeightedSampler(freq[i])
    choices = sampler.sample(3000)
    genotypes = sum([[[0,0], [0,1], [1.1]][x] for x in choices], [])
    initGenotype(pop, genotype=genotypes, loci=i)
```

In the mean time, please keep the ticket open and I will add an option `genotype` to work with `freq` or `prop` when I get a chance.
This is not tested but hopefully you can get the idea.

**Comment by LozWhite** [comment]
I cannot import WeightedSampler from simuPOP.utils? 

"ImportError: cannot import name WeightedSampler"

**Comment by BoPeng** [comment]
My fault, `WeightedSampler` is in the main simuPOP module, not in `simuPOP.utils`.

**Comment by BoPeng** [comment]
ok. Since it is obviously the right thing to do and it is not difficult to add this feature, I have added parameter `genotypes` to operator `InitGenotype`. You will have to compile simuPOP from source or wait for the next release of simuPOP (which will not be far away).
