### ISSUE TITLE
Timeline to 1.1.8 release?

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#23]
Apologies if this is documented somewhere.

**Comment by BoPeng** [comment]
I have started releasing 1.1.8, just need to make sure all tests pass on all supported platforms. I am tight on time though so I expect everything to be done this weekend. 

Note that this will be a Python 3 only release unless you guys are still using Python 2 and request continued support for it.

**Comment by ashander** [comment]
Awesome, I thought it would be close based on time since last release (and
comment you made in another issue).

Python 3 only is great for me

**Comment by ashander** [comment]
Is there any better way to poll teh current user base than a github issue?

**Comment by BoPeng** [comment]
Well, I will send an (perhaps the last) broadcast message through the `simupop-users` mailing list, which has about 200 registered users ...

Anyway, the "current user base" is a moving target and is exactly the reason why I moved from the mailing list to github issues, because every time there was a heated discussion in the mailing list, I would get one or two unsubscription notification from users who have stopped using simuPOP. :-)

**Comment by ashander** [comment]
Note (for other readers) the [1.1.8 release is in process on conda forge](https://github.com/conda-forge/staged-recipes/pull/2349)

**Comment by ashander** [comment]
It's now released [on conda forge](https://github.com/conda-forge/simupop-feedstock)

And available via

```sh
conda config --add channels conda-forge
conda install simupop
```
