### ISSUE TITLE
sexSpecificRecombinator example does not work

### ISSUE THREAD

**Issue by IgnasiLucas** [BoPeng/simuPOP#4]
The example http://simupop.sourceforge.net/manual_release/build/sexSpecificRec.py does not work as intended. No matter what rates are specified, neither paternal nor maternal chromosomes recombine at all.

**Comment by BoPeng** [comment]
If I set malerate to 0.5 and femalerate to 0

```
SubPopulation 0 (), 10 Individuals:
   2: MU 132222003000102 221120330010302 | 030131020101320 030200130020310 |  1 3
   9: FU 301320321221200 110112300210012 | 000230020000020 120001110020330 |  6 5

SubPopulation 0 (), 10 Individuals:
   0: FU 301320321221200 120001110020330 | 030131020101320 221120330010302 |  2 9
```

I can see no recombinant is present. I will see what is going on and get back to you.

**Comment by BoPeng** [comment]
The problem is that the default value of `loci` for in the defintion of `sexSpecificRecombiantor` should be `ALL_AVAIL` instead of `[]`, so you should change the definition to

```
class sexSpecificRecombinator(PyOperator):
    def __init__(self, intensity=0, rates=0, loci=ALL_AVAIL, convMode=NO_CONVERSION,
            maleIntensity=0, maleRates=0, maleLoci=[], maleConvMode=NO_CONVERSION,
            *args, **kwargs):
```

The source of the problem is that `Recombinator` treated `[]` as `ALL_AVAIL` initially but treated it as empty list later on and demanded input `ALL_AVAIL` as all loci. The example was not updated for the change.

**Comment by BoPeng** [comment]
Also the default value for `maleLoci`.
