### ISSUE TITLE
simuPOP conda installation

### ISSUE THREAD

**Issue by EricF2218** [BoPeng/simuPOP#56]
Hi,

I just installed simuPOP using the instructions on your website. The installation seems to have gone fine except that it doesn't seem to have installed the plotter module. Do you know why this could be or how to solve this issue?

Best,

Eric

**Comment by BoPeng** [comment]
Hi, Eric,

The plotter module has been deprecated due to difficulties in maintaining `rpy` connections and working with `matplotlib`. In general you are recommended to output data to files and plot them by yourself (`PyOutput`, `PyEval` etc). If you really like what the `plotter` module offers, you can try to adapt it from the [source code](https://github.com/BoPeng/simuPOP/blob/python2/src/plotter.py) , which should work with only minor syntax changes.

Bo

**Comment by EricF2218** [comment]
Gotcha. Thanks for the quick response!
