### ISSUE TITLE
Graphing number of alleles in simuPOP

### ISSUE THREAD

**Issue by natashaserrao** [BoPeng/simuPOP#73]
Hi Bo,

I am trying to plot the number of alleles over time.
I was trying to use your example from "Source Code 2.3 Demonstration of a Bottleneck Effect", to do so, but keep getting the error, No module named "simuPOP.plotter".

Has this module been removed? If so, how would i go about visualising the example in 2.3?

Thank you very much,
Natasha

**Comment by BoPeng** [comment]
Yes, the plotter module has been deprecated. This module previously used R for plotting but we have had a lot of trouble in keeping up with versions of R and rpy. We latter used `matplotlib` but are still having problems. Since I am trying to focus my attention to key features (simulations) of simuPOP, I have deprecated this module.

If you really need this module, you can get it  from [the python2 branch](https://github.com/BoPeng/simuPOP/blob/python2/src/plotter.py) and try to make it work (e.g. include it in your project and import it as `plotter`). I believe it should mostly work since the module was written with Python3 in mind and a simple `2to3` conversion should make it work with Python3.

If you do not really need to plot things dynamically, what people have done was to use `PyOutput` to write things to a csv file and plot the statistics after the simulation.

**Comment by natashaserrao** [comment]
Thank you Bo!

**Comment by natashaserrao** [comment]
Here is my code I used to plot in matplotlib in case anyone is interested. I exported the number of alleles  for two populations (y1 and y2) at each generation (x1):

import matplotlib.pyplot as plt
import csv

x1=[]
y1=[]
y2=[]


#open just BC population over time
with open('AGAF2.txt', 'r') as csvfile:
    plots=csv.reader(csvfile, delimiter=',')
    for row in plots:
        x1.append(float(row[0]))
        y1.append(float(row[1]))
        y2.append(float(row[2]))

        
plt.plot(x1,y1, 'r--', label='ONP population-migrants')
plt.plot(x1,y2, 'b--', label='BC population')
plt.xlabel('Number of Generations')
plt.ylabel('Number of Alleles')
plt.ylim(0,6)
plt.title('Loss of Alleles over Time')
plt.legend()
plt.show()
